namespace AccessoriesPlus.Content.StatTooltips;

// TODO: fetch wing flight heights + vertical wing speed stats
public class WingStatsCalculator
{
    // TODO: temp, use for testing
    public static readonly Dictionary<int, float?> VanillaFlightHeight = new()
    {
        { ArmorIDs.Wing.CreativeWings, 18 * 16f },
        { ArmorIDs.Wing.AngelWings, 53 * 16f },
        { ArmorIDs.Wing.DemonWings, 53 * 16f },
        { ArmorIDs.Wing.FairyWings, 67 * 16f },
        { ArmorIDs.Wing.FinWings, 67 * 16f },
        { ArmorIDs.Wing.FrozenWings, 67 * 16f },
        { ArmorIDs.Wing.HarpyWings, 67 * 16f },
        { ArmorIDs.Wing.Jetpack, 77 * 16f },
        { ArmorIDs.Wing.RedsWings, 77 * 16f },
        { ArmorIDs.Wing.DTownsWings, 77 * 16f },
        { ArmorIDs.Wing.WillsWings, 77 * 16f },
        { ArmorIDs.Wing.CrownosWings, 77 * 16f },
        { ArmorIDs.Wing.CenxsWings, 77 * 16f },
        { ArmorIDs.Wing.LazuresBarrierPlatform, 77 * 16f },
        { ArmorIDs.Wing.Yoraiz0rsSpell, 77 * 16f },
        { ArmorIDs.Wing.JimsWings, 77 * 16f },
        { ArmorIDs.Wing.SkiphssPaws, 77 * 16f },
        { ArmorIDs.Wing.LokisWings, 77 * 16f },
        { ArmorIDs.Wing.ArkhalisWings, 77 * 16f },
        { ArmorIDs.Wing.LeinforsWings, 77 * 16f },
        { ArmorIDs.Wing.GhostarsWings, 77 * 16f },
        { ArmorIDs.Wing.SafemanWings, 77 * 16f },
        { ArmorIDs.Wing.FoodBarbarianWings, 77 * 16f },
        { ArmorIDs.Wing.GroxTheGreatWings, 77 * 16f },
        { ArmorIDs.Wing.LeafWings, 81 * 16f },
        { ArmorIDs.Wing.BatWings, 81 * 16f },
        { ArmorIDs.Wing.BeeWings, 81 * 16f },
        { ArmorIDs.Wing.ButterflyWings, 81 * 16f },
        { ArmorIDs.Wing.FlameWings, 81 * 16f },
        { ArmorIDs.Wing.Hoverboard, 94 * 16f },
        { ArmorIDs.Wing.BoneWings, 94 * 16f },
        { ArmorIDs.Wing.MothronWings, 94 * 16f },
        { ArmorIDs.Wing.SpectreWings, 94 * 16f },
        { ArmorIDs.Wing.BeetleWings, 94 * 16f },
        { ArmorIDs.Wing.FestiveWings, 107 * 16f },
        { ArmorIDs.Wing.SpookyWings, 107 * 16f },
        { ArmorIDs.Wing.TatteredFairyWings, 107 * 16f },
        { ArmorIDs.Wing.SteampunkWings, 107 * 16f },
        { ArmorIDs.Wing.BetsyWings, 119 * 16f },
        { ArmorIDs.Wing.RainbowWings, 128 * 16f },
        { ArmorIDs.Wing.FishronWings, 143 * 16f },
        { ArmorIDs.Wing.NebulaMantle, 143 * 16f },
        { ArmorIDs.Wing.VortexBooster, 143 * 16f },
        { ArmorIDs.Wing.SolarWings, 167 * 16f },
        { ArmorIDs.Wing.StardustWings, 167 * 16f },
        { ArmorIDs.Wing.LongTrailRainbowWings, 201 * 16f },
    };
}
